# This is a basic workflow to help you get started with Actions

name: Schedule

# Controls when the workflow will run
on:
   schedule:
     - cron: "15,45 * * * *"

env:
  FIRST_NAME: Andreas
  FAV_FOOD: Sushi
  SECRET_MESSAGE: ${{ secrets.SECRET_MESSAGE }} 
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: This is andreas
        run: echo "This is $FIRST_NAME and his favourite food is $FAV_FOOD"

  test2:

    runs-on: ubuntu-latest
    needs: [test1]

    steps:
      - name: testing a secret
        run: echo $SECRET_MESSAGE
    
